/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        white: 'rgb(var(--bg-color) / <alpha-value>)',
        black: 'rgb(var(--text-color) / <alpha-value>)',
        gptDark: "#343541",
        gptDarker: "#202123",
        "on-tertiary-container": "#00304a",
        "inverse-primary": "#ab3600",
        "outline": "#aa897f",
        "inverse-on-surface": "#313030",
        "outline-variant": "#5b4138",
        "secondary-fixed-dim": "#c6c6c7",
        "tertiary": "#8dcdff",
        "primary-fixed": "#ffdbcf",
        "surface-tint": "#ffb59c",
        "on-primary-container": "#561700",
        "surface-bright": "#3a3939",
        "primary-fixed-dim": "#ffb59c",
        "tertiary-container": "#009de4",
        "tertiary-fixed-dim": "#8dcdff",
        "secondary-fixed": "#e2e2e2",
        "surface-container-low": "#1c1b1b",
        "secondary": "#c6c6c7",
        "tertiary-fixed": "#cae6ff",
        "on-primary-fixed-variant": "#832700",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#1a1c1c",
        "on-error": "#690005",
        "on-surface-variant": "#e3bfb3",
        "surface": "#131313",
        "on-primary": "#5c1900",
        "on-secondary-fixed-variant": "#454747",
        "error-container": "#93000a",
        "on-primary-fixed": "#390c00",
        "inverse-surface": "#e5e2e1",
        "primary": "#ffb59c",
        "primary-container": "#ff5f1f",
        "on-secondary": "#2f3131",
        "on-tertiary": "#00344f",
        "surface-container-highest": "#353534",
        "surface-dim": "#131313",
        "background": "#0e0e0e",
        "on-background": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed": "#001e30",
        "secondary-container": "#454747",
        "surface-container-high": "#2a2a2a",
        "surface-variant": "#353534",
        "surface-container": "#201f1f"
      },
    },
  },
  plugins: [],
};
